spring:

  profiles:
    include: oauth

  datasource:
    # url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/s10p31s208?serverTimezone=UTC&Unicode=true&characterEncoding=utf8
    # username: S10P31S208
    # password: HGsiyybsmb
    url: jdbc:mysql://k10s208.p.ssafy.io:3306/bscard
    username: root
    password: ssafy
  jackson:
    time-zone: Asia/Seoul

  mail:
    default-encoding: UTF-8
    host: smtp.naver.com
    port: 587
    username: junwon1131@naver.com
    password: KNY95F5E68R5
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.timeout: 50000
        smtp.starttls.enable: true


  data:
    redis:
      host: localhost
      port: 6379
      password: 'test1234'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

cloud:
  aws:
    credentials:
      access-key: AKIARI2J3RH43CRK24NB
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: ssafybizcard
      stack:
        auto: false


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

server:
  port: 8080
  servlet:
    context-path: /


